import { useCallback, useEffect, useState } from "react";
import { apiJson } from "../api/client";
import { ErrorBox, FeaturePage, MetricCard, EmptyState, StatusPill } from "../components/FeatureShell";
import { formatBytes, formatDate } from "../utils/featureFormat";

type Client={id?:string;name?:string;status?:string;online?:boolean;last_seen?:number;files_uploaded?:number;bytes_uploaded?:number};type Computer={name:string;modified_at:number;size_bytes:number};type Disk={index:number;name:string;root:string;computers:Computer[]};type Library={ok:boolean;configured:boolean;share_name:string;computer_count:number;disks:Disk[];clients:Client[]};type Pairing={code:string;expires_in_seconds:number};
export default function PcBackupsPage(){const[data,setData]=useState<Library|null>(null);const[pair,setPair]=useState<Pairing|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await apiJson<Library>("/api/v1/pc-backups"));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}},[]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);const pairing=async()=>{try{setPair(await apiJson<Pairing>("/api/v1/pc-client/pairing",{method:"POST"}));}catch(e){setError(e instanceof Error?e.message:String(e));}};
 return <FeaturePage title="PC Backup" subtitle="Windows istemcileri ve PC yedek kütüphanesi" actions={<><button className="feature-button" onClick={()=>void load()} disabled={loading}>Yenile</button><button className="feature-button primary" onClick={()=>void pairing()}>PC eşleştirme kodu</button></>}>
 {error&&<ErrorBox message={error}/>} {pair&&<div className="feature-card" style={{marginBottom:16}}><strong>PC eşleştirme kodu</strong><div className="code-box">{pair.code}</div><small>{pair.expires_in_seconds??600} saniye geçerli.</small></div>}
 <div className="metric-grid"><MetricCard label="Yapılandırma" value={data?.configured?"Hazır":"Eksik"}/><MetricCard label="Bilgisayar" value={data?.computer_count??0}/><MetricCard label="İstemci" value={data?.clients?.length??0}/><MetricCard label="Paylaşım" value={data?.share_name??"PhotoOS-PC-Backup"}/></div>
 {!data||data.disks.length===0?<EmptyState>{loading?"Yükleniyor…":"PC Backup diski atanmadı."}</EmptyState>:<div className="feature-grid">{data.disks.map(d=><article className="feature-card" key={d.index}><h3>{d.name}</h3><small>{d.root}</small>{d.computers.length===0?<p>Bu diskte bilgisayar yedeği yok.</p>:d.computers.map(c=><p key={c.name}><strong>{c.name}</strong><br/><small>{formatBytes(c.size_bytes)} · {formatDate(c.modified_at)}</small></p>)}</article>)}</div>}
 {data?.clients?.length?<div className="feature-table-wrap" style={{marginTop:16}}><table className="feature-table"><thead><tr><th>İstemci</th><th>Durum</th><th>Dosya</th><th>Boyut</th><th>Son görülme</th></tr></thead><tbody>{data.clients.map((c,i)=><tr key={c.id??i}><td>{c.name??c.id??"PC"}</td><td><StatusPill ok={c.online??c.status==="online"} label={c.status??(c.online?"online":"offline")}/></td><td>{c.files_uploaded??0}</td><td>{formatBytes(c.bytes_uploaded)}</td><td>{formatDate(c.last_seen)}</td></tr>)}</tbody></table></div>:null}
 </FeaturePage>}
